### ISSUE TITLE
Alternative using fzf

### ISSUE THREAD

**Issue by xeruf** [zdharma-continuum/history-search-multi-word#1]
Maybe interesting to you - an alias that seems to do essentially the same but interactively, though without syntax highlighting

```bash
alias hist='print -z $(history | tac | fzf --tiebreak=index | sed "s|^ \+||" | cut -d" " -f5-)'
```

**Comment by alichtman** [comment]
I have this hotkey'd to `Ctrl-R`. It's pretty sweet. I don't use this plugin.
